/*********************************************************
*Class        :  ABCL_LitmusSurveyWrapper
*Author       :  Santosh V
*Created Date :  
*Last Modified:  
*Description  :  Class for Litmus API Integration Wrapper
*********************************************************/

public class ABCL_LitmusSurveyWrapper {
    public String tag_category;
    public String tag_created_by;
    public String tag_sla_deadline;
    public String tag_created_on;
    public String tag_case_type;
    public String tag_source;
    public String tag_case_id;
    public String tag_resolved_on;
    public String name;
    public String tag_owner;
    public String tag_case_sub_type;
    public String tag_loan_account_no;
    public String userEmail;
    public String tag_ftr_nftr;
    public String userPhone;
    public String tag_ageing;
    public String appId;

    public String panorarn;
    public String caller_type;
    public String lob;
    public String type;
}