public class ABHFL_EbotWrapper {
	
    public class EbotResponseWrapper{
        public string CASEID;
        public string CASESUBTYPE;
        public string COMMENT;
        public string OWNERFULLNAME;
        public string CONFIDENCESCORE;
        public String ASONDATE;
        public String DISBURSTMENTTYPE;
        public String FROMDATE;
        public Integer FROMYEAR;
        public String ISCORRUPTED;
        public String ISMULTILAN;
        public String ISMULTIPLEDATEFORMATE;
        public String ISREGISTRED;
        public String ISREGULATOR;
        public String ISREPEAT;
        public String ISSMT;
        public String ISTRAIL;
        public String LANCOMMENT;
        public String LOB;
        public String TODATE;
        public Integer TOYEAR;
        public String Template1;
        public String Template2;
        public String Template3;
        public String UNREGISTEREDCATEGORY;
        public List<String> LAN_NOS;
    }
}