/*********************************************************
*Class        :  ABHI_WelcomeBotWrapper
*Author       :  Aditee Churiwala
*Created Date :  09/30/2024
*Last Modified:  09/30/2024
*@description :  Welcome Bot wrapper
*********************************************************/
public class ABHI_WelcomeBotWrapper {
        public String requestId;
        public String serviceId;
        public String msisdn;
        public String language;
        public String group_or_retail;
        public String policy_holder_name;
        public String policy_type;
        public String policy_number;
        public String policy_name;
        public String customer_id;
        public String State;
        public String Policy_Channel;
        public String Policy_Source;
    	public String dispositionId;
}