/**
* @description       : Constant class to store all the resable variables at one place
* @author            : rsinghnagar@salesforce.com
* @group             : 
* @last modified on  : 13-08-2024
* @last modified by  : Neeraj Kumar
* Description        : This will contain the strings to be used for ABSLAMC
**/
public with Sharing class ABSLAMC_Constants {
    public static final String OPEN_STAGE = 'Open';
    public static final String REPLY_RECEIVED_FROM_APP_SUPPORT = 'Reply Received from App Support';
    public static final String ISSUE_MANAGEMENT_UNIT = 'Issue Management Unit';   
    public static final String AWAITING_RESPONSE_FROM_APP_SUPPORT = 'Awaiting Response from App Support'; 
    
}