/*********************************************************
*Class        :  ASF_EmailRelayLoadBalancerTest 
*Author       :  Virendra Patil
*Description  :  Test class for ASF_EmailRelayLoadBalancer.
*********************************************************/
@isTest
public class ASF_EmailRelayLoadBalancerTest {
    @isTest
    public static void execute(){
        ASF_EmailRelayLoadBalancer.execute(null);
    }
}