name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to deploy to
        options:
          - uat-sandbox
        default: 'uat-sandbox'
        required: true
      validateOnly:
        description: 'Run the deployment as validation only'
        type: boolean
        default: false

jobs:

  deploy-uat-sandbox:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'uat-sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to sit sandbox
        uses: ./.github/actions/deploy-environment
        with:
          sfdx_auth_url: ${{ secrets.SFDX_ABCL_UAT_FS }}
          environmentName: ${{ github.event.inputs.environment }}
          validateOnly: ${{ github.event.inputs.validateOnly }}
  
